name: Frontend CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          cd frontend
          npm ci

      - name: Build Angular (Production)
        run: |
          cd frontend
          npm run build -- --configuration production --output-path=dist

      - name: Login Fly.io
        uses: superfly/flyctl-actions@1.0
        with:
          api_key: ${{ secrets.FLY_API_TOKEN }}

      - name: Deploy to Fly.io
        run: |
          cd frontend
          fly deploy --remote-only
